/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * DL4JNetworkBuilder.java
 * Copyright (C) 2014 University of Waikato, Hamilton, New Zealand
 */
package adams.flow.source;

import adams.flow.core.Token;
import adams.flow.source.nnbuilder.AbstractNetworkBuilder;
import adams.flow.source.nnbuilder.DBNBuilder;

/**
 <!-- globalinfo-start -->
 <!-- globalinfo-end -->
 *
 <!-- flow-summary-start -->
 <!-- flow-summary-end -->
 *
 <!-- options-start -->
 <!-- options-end -->
 *
 * @author  fracpete (fracpete at waikato dot ac dot nz)
 * @version $Revision$
 */
public class DL4JNetworkBuilder
  extends AbstractSimpleSource {

  /** for serialization. */
  private static final long serialVersionUID = 6315555615087637809L;
  
  /** the network builder to use. */
  protected AbstractNetworkBuilder m_Builder;
  
  /**
   * Returns a string describing the object.
   *
   * @return 			a description suitable for displaying in the gui
   */
  @Override
  public String globalInfo() {
    return "Outputs a network generated by the specified builder.";
  }

  /**
   * Adds options to the internal list of options.
   */
  @Override
  public void defineOptions() {
    super.defineOptions();

    m_OptionManager.add(
	    "builder", "builder",
	    new DBNBuilder());
  }

  /**
   * Sets the network builder.
   *
   * @param value	the builder
   */
  public void setBuilder(AbstractNetworkBuilder value) {
    m_Builder = value;
    reset();
  }

  /**
   * Returns the network builder.
   *
   * @return		the builder
   */
  public AbstractNetworkBuilder getBuilder() {
    return m_Builder;
  }

  /**
   * Returns the tip text for this property.
   *
   * @return 		tip text for this property suitable for
   * 			displaying in the GUI or for listing the options.
   */
  public String builderTipText() {
    return "The builder to use for generating the network.";
  }

  /**
   * Returns the class of objects that it generates.
   *
   * @return		the Class of the generated tokens
   */
  @Override
  public Class[] generates() {
    if (m_Builder != null)
      return new Class[]{m_Builder.generates()};
    else
      return new Class[]{Object.class};
  }

  /**
   * Executes the flow item.
   *
   * @return		null if everything is fine, otherwise error message
   */
  @Override
  protected String doExecute() {
    String	result;
    
    result = null;
    
    try {
      m_OutputToken = new Token(m_Builder.generateNetwork());
    }
    catch (Exception e) {
      result = handleException("Failed to configure network!", e);
    }

    return result;
  }
}
