/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Wave.java
 * Copyright (C) 2018 University of Waikato, Hamilton, NZ
 */

package adams.flow.transformer.audiodata;

import adams.core.Utils;
import adams.core.base.BaseURL;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.URL;

/**
 * Reads data from WAV files or URLs.
 *
 * @author FracPete (fracpete at waikato dot ac dot nz)
 */
public class Wave
  extends AbstractAudioDataReader<com.musicg.wave.Wave> {

  private static final long serialVersionUID = -8099230864926096497L;

  /**
   * Returns a string describing the object.
   *
   * @return 			a description suitable for displaying in the gui
   */
  @Override
  public String globalInfo() {
    return "Reads data from WAV files or URLs.";
  }

  /**
   * The accepted input types.
   *
   * @return		the input types
   */
  @Override
  public Class[] accepts() {
    return new Class[]{String.class, URL.class, BaseURL.class};
  }

  /**
   * The output generated by the reader.
   *
   * @return		the output type
   */
  @Override
  public Class generates() {
    return com.musicg.wave.Wave.class;
  }

  /**
   * Reads the data from the input.
   *
   * @param input	the input data
   * @return		the generated output
   * @throws Exception	if reading fails
   */
  @Override
  protected com.musicg.wave.Wave doRead(Object input) throws Exception {
    InputStream		is;

    is     = null;
    if (input instanceof String)
      is = new BufferedInputStream(new FileInputStream((String) input));
    else if (input instanceof URL)
      is = new BufferedInputStream(((URL) input).openStream());
    else if (input instanceof BaseURL)
      is = new BufferedInputStream(((BaseURL) input).urlValue().openStream());

    if (is != null)
      return new com.musicg.wave.Wave(is);
    else
      throw new IllegalStateException("Unhandled input data: " + Utils.classToString(input));
  }
}
